# Generated by Django 5.0.4 on 2024-06-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
