# Generated by Django 5.0.4 on 2024-06-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_rename_messagereactions_roomreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagereactions', to='chatapp.message'),
        ),
        migrations.AlterField(
            model_name='roomreaction',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomreactions', to='chatapp.room'),
        ),
    ]
