# Generated by Django 5.0.4 on 2024-06-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_remove_roomreaction_room_remove_roomreaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlike_set', to='chatapp.roomcomment'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreply_set', to='chatapp.roomcomment'),
        ),
        migrations.AlterField(
            model_name='roomcomment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomcomment_set', to='chatapp.room'),
        ),
        migrations.AlterField(
            model_name='roomlike',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomlike_set', to='chatapp.room'),
        ),
    ]
