# Generated by Django 5.0.4 on 2024-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_alter_commentlike_comment_alter_commentreply_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
